export declare enum ArtNodeType {
    Unknown = "Unknown",
    Root = "Root",
    Header1 = "Header1",
    Header2 = "Header2",
    Header3 = "Header3",
    Header4 = "Header4",
    Header5 = "Header5",
    Header6 = "Header6",
    Paragraph = "Paragraph",
    Text = "Text",
    Emphasis = "Emphasis",
    Strong = "Strong",
    Span = "Span",
    Image = "Image",
    Link = "Link",
    PreformattedText = "PreformattedText",
    Code = "Code",
    HighlightCode = "HighlightCode",
    OrderedList = "OrderedList",
    UnderedList = "UnderedList",
    ListItem = "ListItem"
}
